// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261003113438_AddMoreCustomersSeed")]
    partial class AddMoreCustomersSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bánh kẹo & Đồ ăn vặt",
                            Description = "Snack, bánh quy, kẹo dẻo"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Nước giải khát & Trà",
                            Description = "Nước ngọt, nước khoáng, trà"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sữa & Sản phẩm từ sữa",
                            Description = "Sữa tươi, sữa chua, phô mai"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Mì gói & Thực phẩm ăn liền",
                            Description = "Mì ăn liền, phở khô, cháo gói"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị & Dầu ăn",
                            Description = "Nước mắm, hạt nêm, dầu thực vật"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Hà Nội",
                            CustomerName = "Nguyễn Văn A",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "TP.HCM",
                            CustomerName = "Trần Thị B",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 50
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "Đà Nẵng",
                            CustomerName = "Lê Văn C",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 10
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "Cần Thơ",
                            CustomerName = "Phạm Minh Đức",
                            MembershipRank = "Bạch Kim",
                            PhoneNumber = "0971234567",
                            RewardPoints = 320
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "Hải Phòng",
                            CustomerName = "Hoàng Thu Thảo",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0934567890",
                            RewardPoints = 180
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "Bình Dương",
                            CustomerName = "Đỗ Quốc Anh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0945678901",
                            RewardPoints = 25
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "Đồng Nai",
                            CustomerName = "Vũ Mỹ Linh",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0967890123",
                            RewardPoints = 75
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "Quảng Ninh",
                            CustomerName = "Bùi Tấn Phát",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0923456789",
                            RewardPoints = 210
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "Huế",
                            CustomerName = "Đặng Hồng Hạnh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0956789012",
                            RewardPoints = 0
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "Nha Trang",
                            CustomerName = "Ngô Gia Bảo",
                            MembershipRank = "Bạch Kim",
                            PhoneNumber = "0987654321",
                            RewardPoints = 500
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "TP.HCM",
                            CustomerName = "Dương Ngọc Trinh",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912345678",
                            RewardPoints = 90
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "Hà Nội",
                            CustomerName = "Lý Khánh Vân",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0938765432",
                            RewardPoints = 160
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "Vũng Tàu",
                            CustomerName = "Mai Xuân Trường",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0941239876",
                            RewardPoints = 15
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "Lâm Đồng",
                            CustomerName = "Trịnh Kim Ngân",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0965432109",
                            RewardPoints = 85
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "Kiên Giang",
                            CustomerName = "Đoàn Hải Nam",
                            MembershipRank = "Bạch Kim",
                            PhoneNumber = "0978901234",
                            RewardPoints = 410
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
